name: LandGuilds
main: xyz.dec0de.landguilds.Main
version: 1.0
api-version: 1.13
website: https://dec0de.xyz
description: Land Claiming & Guilds
authors: [Nyarrth]
commands:
  lands:
    aliases: [l, land, ll]
    description: Lands Command
  guilds:
    aliases: [g, guild, gg]
    description: Guilds Command
  map:
    aliases: [mapo, mapmap, yaymaps]
    description: Show a map of the claimed chunks
  lgadmin:
    aliases: [landguildsadmin, ladmin, gadmin]
    description: Operator command
  landguilds:
    aliases: [lg, landguild]
    description: Main Command