name: ArchesLands
main: xyz.dec0de.archesmc.lands.Main
version: 1.0
api-version: 1.13
website: https://dec0de.xyz
description: Land Claiming & Guilds
commands:
  lands:
    aliases: [l, land, ll]
    description: Lands Command
  guilds:
    aliases: [g, guild, gg]
    description: Guilds Command